plugins {
	// Apply the foojay-resolver plugin to allow automatic download of JDKs
	id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
	id 'com.google.cloud.artifactregistry.gradle-plugin' version '2.2.5' apply false
}

def activeProfile = startParameter.projectProperties['profile']

if (activeProfile == 'google') {
	println "LOG: Profile google detected. Applying Artifact Registry plugin..."
	apply plugin: 'com.google.cloud.artifactregistry.gradle-plugin'
} else {
	println "LOG: Default profile active. Google Cloud plugin skipped."
}

rootProject.name = 'dwh-migration-tools'
include(
	':dumper:lib-common',
	':dumper:lib-dumper-spi',
	':dumper:lib-ext-bigquery',
	':dumper:lib-ext-hive-metastore',
	':dumper:connector-api',
	':dumper:app',
	':dumper:connectors:airflow',
	':dumper:connectors:bigquery',
	':dumper:connectors:cloudera',
	':dumper:connectors:generic',
	':dumper:connectors:greenplum',
	':dumper:connectors:hadoop',
	':dumper:connectors:hdfs',
	':dumper:connectors:hive',
	':dumper:connectors:mysql',
	':dumper:connectors:netezza',
	':dumper:connectors:oracle',
	':dumper:connectors:postgresql',
	':dumper:connectors:ranger',
	':dumper:connectors:redshift',
	':dumper:connectors:snowflake',
	':dumper:connectors:sqlserver',
	':dumper:connectors:teradata',
	':dumper:connectors:vertica'
)
