/*
 * Copyright 2022-2025 Google LLC
 * Copyright 2013-2021 CompilerWorks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
plugins {
    id 'dwh-migration-dumper.java-library-conventions'
}

dependencies {
    api project(':dumper:lib-common')
    api project(':dumper:lib-dumper-spi')

    api libs.guava
    api libs.jopt.simple
    api libs.spring.jdbc

    implementation libs.jdiagnostics
    implementation libs.spring.core
    implementation libs.hikaricp
    api libs.apache.commons.csv
    api libs.apache.commons.lang3

    implementation libs.commons.io
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jackson.datatype.guava

    testFixturesApi libs.junit
    testFixturesImplementation libs.apache.commons.lang3
}

dependencyLocking {
    lockAllConfigurations()
}
